import { useEffect, useState } from 'react';
import { AlertTriangle, Check, Copy, Download, Maximize2, MessageSquare, RefreshCw, X } from 'lucide-react';
import { copilotApi } from '../../api';
import type { VisualVariation } from '../../types';
import { EmptyArtifact, StatusPill, strictContinuation } from '../shared/ui';
import type { WorkspaceProps } from '../shared/ui';
import { StrictProductionPanel } from '../strict-continuation/StrictProductionPanel';

function VisualLightbox({ variation, index, onClose, onExport }: { variation: VisualVariation; index: number; onClose: () => void; onExport: () => void }) {
  const outputSize = variation.output_width && variation.output_height ? `${variation.output_width}×${variation.output_height}` : variation.target_size;
  return <div className="lightbox" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="lightbox-panel"><header><div><span>V{index + 1} · {variation.strategy}</span><b>{variation.strategy === 'conservative' ? '保守继承' : variation.strategy === 'expressive' ? '表现强化' : '局部创新'}</b></div><div><button className="button button--secondary" onClick={onExport}><Download size={15} />导出 PNG</button><button className="icon-button" onClick={onClose}><X size={18} /></button></div></header><img src={variation.image_url} alt={variation.strategy} /><footer><code>布局：{variation.layout_name || variation.layout_version}</code><code>风格：{variation.style_name || variation.style_version}</code><code>成图：{outputSize ? `${outputSize}${variation.canvas_spec?.aspect_ratio ? ` · ${variation.canvas_spec.aspect_ratio}` : ''}` : '历史结果未记录像素'}</code>{variation.canvas_spec && <code>设计画布：{variation.canvas_spec.width}×{variation.canvas_spec.height}</code>}</footer></div></div>;
}

// Visual exploration workspace: owns variation selection, review notes and
// lightbox state; the strict production chain renders below via its own panel.
export function VisualWorkspace({ project, busy, run, canCancel, onCancel }: WorkspaceProps & { canCancel: boolean; onCancel: () => void }) {
  const artifact = project.artifacts.visualResults;
  const variations = artifact?.variations || [];
  const strategies = ['conservative', 'expressive', 'innovative'];
  const missingStrategies = strategies.filter((strategy) => !variations.some((variation) => variation.strategy === strategy));
  const approvedIds = ((artifact?.review as Record<string, unknown>)?.selected_variation_ids as string[]) || [];
  const [selected, setSelected] = useState<string[]>(approvedIds.length ? approvedIds : variations[0]?.id ? [variations[0].id] : []);
  const [lightbox, setLightbox] = useState('');
  const [notes, setNotes] = useState(String((artifact?.review as Record<string, unknown>)?.notes || ''));
  useEffect(() => { setSelected(approvedIds.length ? approvedIds : variations[0]?.id ? [variations[0].id] : []); }, [project.id, artifact?.version, variations.length]);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const active = variations.find((item) => item.id === lightbox);
  const approve = (mode: 'selected' | 'combine') => run(() => copilotApi.approveArtifact(project.id, 'visual-results', { selectedIds: selected, mode, notes }), { label: mode === 'combine' ? '保存组合方向' : '批准视觉方向', stage: 'visual_exploration' });
  const strict = strictContinuation(project);
  return <>
    <div className="workspace-content visual-workspace">
    <section className="workspace-heading"><div><span className="kicker">04 · AI VISUAL EXPLORATION</span><h1>评审、组合并交付视觉方向</h1><p>支持多选组合、全屏检查、批注意见、批准版本、全部否决和单张导出。</p></div>{variations.length > 0 && <StatusPill status={artifact?.status || 'reviewed'} />}</section>
    {!variations.length ? <EmptyArtifact title={busy ? '正在生成视觉方向…' : '尚未生成视觉探索'} copy={busy ? '结果会逐张写入；可以停止剩余任务，已完成图片不会丢失。' : '批准并锁定风格规范后开始生图。'} action={canCancel ? <button className="button button--ghost" onClick={onCancel}>停止剩余任务</button> : undefined} /> : <>{artifact?.status === 'stale' && <div className="quality-warning"><AlertTriangle size={16} /><div><b>结果依据已变化</b><p>布局、风格或输入已更新，这些图片只保留用于对照，不能继续批准。</p></div></div>}<div className={`visual-grid is-${project.canvas_spec?.orientation || 'landscape'}`}>{variations.map((variation, index) => { const outputSize = variation.output_width && variation.output_height ? `${variation.output_width}×${variation.output_height}` : variation.target_size; return <article key={variation.id} className={`visual-card ${selected.includes(variation.id) ? 'is-selected' : ''}`}><button className="visual-preview-button" onClick={() => setLightbox(variation.id)}><div className="visual-image" style={{ aspectRatio: variation.output_width && variation.output_height ? `${variation.output_width}/${variation.output_height}` : variation.canvas_spec ? `${variation.canvas_spec.width}/${variation.canvas_spec.height}` : project.canvas_spec ? `${project.canvas_spec.width}/${project.canvas_spec.height}` : '16/9' }}><img src={variation.image_url} alt={variation.strategy} /><span>V{index + 1}</span><em><Maximize2 size={14} />全屏检查</em></div></button><div className="visual-card-copy"><div><span>{variation.strategy}</span><b>{variation.strategy === 'conservative' ? '保守继承' : variation.strategy === 'expressive' ? '表现强化' : '局部创新'}</b></div><label><input type="checkbox" disabled={artifact?.status === 'stale'} checked={selected.includes(variation.id)} onChange={() => toggle(variation.id)} />加入评审选择</label><small>{variation.layout_name || variation.layout_version} · {variation.style_name || variation.style_version}</small><small>{outputSize ? `成图 ${outputSize}${variation.canvas_spec?.aspect_ratio ? ` · ${variation.canvas_spec.aspect_ratio}` : ''}` : '历史结果未记录实际像素'}</small><button className="retry-variation" disabled={busy || artifact?.status === 'stale'} onClick={() => run(() => copilotApi.runStage(project.id, 'visual_exploration', { strategies: [variation.strategy], preserveExisting: true, feedback: notes }), { label: `重新生成 ${variation.strategy} 方向`, stage: 'visual_exploration', total: 1 })}><RefreshCw size={12} />仅重试此方向</button></div></article>; })}</div><div className="visual-review-panel"><label><MessageSquare size={16} /><span>评审批注 / 下一轮反馈</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="例如：保留 V2 的主视觉层级，采用 V1 的属性卡片；降低紫色发光强度，放大升级前后数值差。" /></label><div><b>已选择 {selected.length} 个方向</b><small>{artifact?.status === 'approved' ? '评审决策已写入 Artifact，可随时重新选择并产生新版本。' : '选择一个批准，或选择两个以上进行组合。'}</small></div></div></>}
    </div>
    <div className="workspace-footer visual-footer">{canCancel ? <button className="button button--ghost" onClick={onCancel}><X size={15} />停止剩余任务</button> : missingStrategies.length > 0 && artifact?.status !== 'stale' ? <button className="button button--ghost" disabled={busy} onClick={() => run(() => copilotApi.runStage(project.id, 'visual_exploration', { strategies: missingStrategies, preserveExisting: true }), { label: `补全 ${missingStrategies.length} 个方向`, stage: 'visual_exploration', total: missingStrategies.length })}><RefreshCw size={15} />补全缺失方向</button> : <button className="button button--ghost" disabled={busy || artifact?.status === 'stale'} onClick={() => run(() => copilotApi.updateArtifact(project.id, 'visual-results', { status: 'rejected', review_notes: notes }), { label: '记录全部否决', stage: 'visual_exploration' }).then(() => run(() => copilotApi.runStage(project.id, 'visual_exploration', { feedback: notes }), { label: '根据反馈重新探索', stage: 'visual_exploration', total: 3 }))}><RefreshCw size={15} />全部否决并重探</button>}<div><button className="button button--secondary" disabled={busy || artifact?.status === 'stale' || selected.length < 2} onClick={() => approve('combine')}><Copy size={15} />组合所选</button><button className="button button--primary" disabled={busy || artifact?.status === 'stale' || selected.length !== 1} onClick={() => approve('selected')}><Check size={16} />批准所选方向</button></div></div>
    {strict && variations.length > 0 && <StrictProductionPanel project={project} underlayId={selected[0] || variations[0]?.id} busy={busy} run={run} />}
    {active && <VisualLightbox variation={active} index={variations.indexOf(active)} onClose={() => setLightbox('')} onExport={() => copilotApi.exportVisual(project.id, active.id)} />}
    </>;
}
