import type { DesignProject } from '../../types';

// Fidelity evidence workbench: read-only Final PNG pixel evidence plus a
// structured pass/fail breakdown so gate failures are readable without JSON.
export function FidelityWorkbench({ project }: { project: DesignProject }) {
  const report = project.artifacts.fidelityReport;
  const output = project.artifacts.compositionOutput;
  const issues = Array.isArray(report?.issues) ? (report?.issues as Array<Record<string, unknown>>) || [] : [];
  const checks = Array.isArray(report?.checks) ? (report?.checks as Array<Record<string, unknown>>) || [] : [];
  return <section className="evidence-workbench fidelity-workbench" data-testid="fidelity-workbench"><header><span>FIDELITY WORKBENCH</span><b>只读像素证据与最终输出</b>{report && <em className={`fidelity-status ${report.status === 'passed' ? 'is-ready' : 'is-failed'}`} data-testid="fidelity-status">{String(report.status)}</em>}</header><div><article><b>Final PNG</b>{output ? <><small>{String(output.path)} · {String(output.width)}×{String(output.height)}</small><code>{String(output.hash)}</code></> : <small>尚未生成</small>}</article><article><b>检查结果</b>{report ? <><small>{String(report.status)} · V{String(report.version || 1)}</small>{issues.length > 0 && <ul className="fidelity-issues" role="alert" data-testid="fidelity-issues">{issues.map((issue, index) => <li key={`${index}-${String(issue.code || issue.message || issue.rule || '')}`}>{issue.code ? <code data-testid="fidelity-issue-code">{String(issue.code)}</code> : null}<span>{String(issue.message || issue.rule || JSON.stringify(issue))}</span></li>)}</ul>}{checks.length > 0 && <ul className="fidelity-checks">{checks.map((check) => <li key={String(check.id || check.name || '')} className={check.status === 'passed' || check.ok ? 'is-ready' : 'is-failed'}>{String(check.id || check.name || '')}<small>{String(check.status ?? (check.ok ? 'passed' : 'failed'))}</small></li>)}</ul>}<details><summary>完整证据 JSON</summary><pre>{JSON.stringify({ source: report.source, metrics: report.metrics, checks: report.checks, issues: report.issues, evidence: report.evidence }, null, 2)}</pre></details></> : <small>尚未运行</small>}</article></div></section>;
}
