// Frozen, single-source registry of every public error code the pipeline can
// throw or report. Services must reference ERROR_CODES instead of inlining
// string literals so docs (ERROR-CATALOG.md) and code can be validated
// bidirectionally by scripts/check-error-docs.cjs.
const ERROR_CODES = Object.freeze({
  // Screen scoping (projectStore / main IPC)
  SCREEN_ID_REQUIRED: 'SCREEN_ID_REQUIRED',
  SCREEN_NOT_FOUND: 'SCREEN_NOT_FOUND',
  SCREEN_CONTEXT_MISMATCH: 'SCREEN_CONTEXT_MISMATCH',
  // Clone transaction integrity (projectStore, M4-K2)
  CLONE_ROLLBACK_INCOMPLETE: 'CLONE_ROLLBACK_INCOMPLETE',
  // Pipeline stage gates (designPipeline)
  FONT_MANIFEST_REQUIRED: 'FONT_MANIFEST_REQUIRED',
  COMPONENT_CONTRACT_REQUIRED: 'COMPONENT_CONTRACT_REQUIRED',
  BINDING_COVERAGE_INCOMPLETE: 'BINDING_COVERAGE_INCOMPLETE',
  REFERENCE_OMISSIONS_CONFIRMATION_REQUIRED: 'REFERENCE_OMISSIONS_CONFIRMATION_REQUIRED',
  UNDERLAY_SPEC_REQUIRED: 'UNDERLAY_SPEC_REQUIRED',
  STYLE_CONTRACT_INVALID: 'STYLE_CONTRACT_INVALID',
  LAYOUT_CONSTRAINT_VIOLATION: 'LAYOUT_CONSTRAINT_VIOLATION',
  REFERENCE_INVENTORY_EMPTY: 'REFERENCE_INVENTORY_EMPTY',
  // Approval freshness gate (designPipeline)
  STALE_REAPPROVAL_BLOCKED: 'STALE_REAPPROVAL_BLOCKED',
  // Screen contract approval revalidation (AUD-06)
  SCREEN_CONTRACT_APPROVAL_INVALID: 'SCREEN_CONTRACT_APPROVAL_INVALID',
  SCREEN_CONTRACT_COVERAGE_INCOMPLETE: 'SCREEN_CONTRACT_COVERAGE_INCOMPLETE',
  // Route-cycle legacy repair (flowStateRepair)
  ROUTE_CYCLE_REPAIR_INELIGIBLE: 'ROUTE_CYCLE_REPAIR_INELIGIBLE',
  // Typography gates (typographyAssets / typographyRenderer)
  FONT_LICENSE_CONFIRMATION_REQUIRED: 'FONT_LICENSE_CONFIRMATION_REQUIRED',
  FONT_EXACT_CONFIRMATION_REQUIRED: 'FONT_EXACT_CONFIRMATION_REQUIRED',
  FONT_CONFIRMATION_ACTION_REQUIRED: 'FONT_CONFIRMATION_ACTION_REQUIRED',
  FONT_ASSET_HASH_MISMATCH: 'FONT_ASSET_HASH_MISMATCH',
  FONT_ACTUAL_LOAD_FAILED: 'FONT_ACTUAL_LOAD_FAILED',
  // Component kit gates (componentKit via designPipeline)
  VECTOR_TOKEN_SOURCE_REQUIRED: 'VECTOR_TOKEN_SOURCE_REQUIRED',
  COMPONENT_ASSET_HASH_MISMATCH: 'COMPONENT_ASSET_HASH_MISMATCH',
  COMPONENT_RENDERER_MISSING: 'COMPONENT_RENDERER_MISSING',
  EXACT_NON_UNIFORM_SCALE: 'EXACT_NON_UNIFORM_SCALE',
  EXACT_SCALE_OUT_OF_POLICY: 'EXACT_SCALE_OUT_OF_POLICY',
  // Composition and final output (compositor / compositionRenderer)
  COMPOSITION_GATE_FAILED: 'COMPOSITION_GATE_FAILED',
  // 证据链匹配与视觉绑定新鲜度（designPipeline / compositionRenderer）
  VISUAL_VARIATION_NOT_FOUND: 'VISUAL_VARIATION_NOT_FOUND',
  UNDERLAY_EVIDENCE_MISMATCH: 'UNDERLAY_EVIDENCE_MISMATCH',
  UNDERLAY_EVIDENCE_STALE: 'UNDERLAY_EVIDENCE_STALE',
  VISUAL_RESULTS_BINDING_STALE: 'VISUAL_RESULTS_BINDING_STALE',
  COMPOSITION_OUTPUT_MISSING: 'COMPOSITION_OUTPUT_MISSING',
  COMPOSITION_OUTPUT_UNREADABLE: 'COMPOSITION_OUTPUT_UNREADABLE',
  COMPOSITION_OUTPUT_INVALID: 'COMPOSITION_OUTPUT_INVALID',
  COMPOSITION_OUTPUT_HASH_MISMATCH: 'COMPOSITION_OUTPUT_HASH_MISMATCH',
  COMPOSITION_OUTPUT_DIMENSION_MISMATCH: 'COMPOSITION_OUTPUT_DIMENSION_MISMATCH',
  FINAL_OUTPUT_REQUIRED: 'FINAL_OUTPUT_REQUIRED',
  FINAL_APPROVAL_REQUIRED: 'FINAL_APPROVAL_REQUIRED',
  FINAL_EXPORT_BLOCKED: 'FINAL_EXPORT_BLOCKED',
  FINAL_EXPORT_HASH_MISMATCH: 'FINAL_EXPORT_HASH_MISMATCH',
  GENERATED_EVIDENCE_READ_ONLY: 'GENERATED_EVIDENCE_READ_ONLY',
  // Fidelity gate (fidelity / designPipeline)
  FIDELITY_GATE_FAILED: 'FIDELITY_GATE_FAILED',
  FIDELITY_OUTPUT_STALE: 'FIDELITY_OUTPUT_STALE',
  FIDELITY_EVIDENCE_STALE: 'FIDELITY_EVIDENCE_STALE',
  FIDELITY_CURRENT_EVIDENCE_FAILED: 'FIDELITY_CURRENT_EVIDENCE_FAILED',
  // Underlay repair and manual review (underlayRepair / designPipeline)
  UNDERLAY_REPAIR_LIMIT: 'UNDERLAY_REPAIR_LIMIT',
  UNDERLAY_MANUAL_REVIEW_NOT_REQUIRED: 'UNDERLAY_MANUAL_REVIEW_NOT_REQUIRED',
  INPAINT_NOT_AVAILABLE: 'INPAINT_NOT_AVAILABLE',
  REPAIR_OUTPUT_MISSING: 'REPAIR_OUTPUT_MISSING',
  REPAIR_EVIDENCE_INCOMPLETE: 'REPAIR_EVIDENCE_INCOMPLETE',
  // Provider image handling (kunpoClient)
  TRANSIENT_IMAGE_UNSUPPORTED: 'TRANSIENT_IMAGE_UNSUPPORTED',
  TRANSIENT_IMAGE_SIZE_INVALID: 'TRANSIENT_IMAGE_SIZE_INVALID',
  TRANSIENT_IMAGE_RATIO_MISMATCH: 'TRANSIENT_IMAGE_RATIO_MISMATCH',
  TRANSIENT_IMAGE_DECODE_FAILED: 'TRANSIENT_IMAGE_DECODE_FAILED',
  TRANSIENT_IMAGE_DOWNLOAD_FAILED: 'TRANSIENT_IMAGE_DOWNLOAD_FAILED',
  UNTRUSTED_IMAGE_LOCATION: 'UNTRUSTED_IMAGE_LOCATION',
  // Reference pack capacity (kunpoClient)
  REFERENCE_CAPACITY_EXCEEDED: 'REFERENCE_CAPACITY_EXCEEDED',
  // Migration testing hook (migrations)
  MIGRATION_FAULT_INJECTED: 'MIGRATION_FAULT_INJECTED'
});

// Binding semantic validation codes (componentBindings / compositor). They
// are reported inside validateBindings error strings and thrown by the strict
// compositor; kept as their own frozen registry and documented in
// ERROR-CATALOG.md. check-error-docs does not validate this group yet: the
// BINDING_* exemption is removed in the documentation fact-integrity follow-up.
const BINDING_VALIDATION_CODES = Object.freeze({
  BINDING_COMPONENT_NOT_SELECTED: 'BINDING_COMPONENT_NOT_SELECTED',
  BINDING_COMPONENT_NOT_APPROVED: 'BINDING_COMPONENT_NOT_APPROVED',
  BINDING_COMPONENT_STATE_MISSING: 'BINDING_COMPONENT_STATE_MISSING',
  BINDING_COMPONENT_CATEGORY_MISMATCH: 'BINDING_COMPONENT_CATEGORY_MISMATCH',
  BINDING_FONT_ROLE_MISMATCH: 'BINDING_FONT_ROLE_MISMATCH',
  BINDING_FONT_ROLE_MISSING: 'BINDING_FONT_ROLE_MISSING',
  BINDING_UNKNOWN_CONTROL_ROLE: 'BINDING_UNKNOWN_CONTROL_ROLE',
  BINDING_STATE_REQUIRED: 'BINDING_STATE_REQUIRED',
  BINDING_FONT_ROLE_REQUIRED: 'BINDING_FONT_ROLE_REQUIRED',
  BINDING_GENERIC_ROLE_UNRESOLVED: 'BINDING_GENERIC_ROLE_UNRESOLVED'
});

// Codes embedded in Fidelity Report issue entries (reported, not thrown).
const FIDELITY_ISSUE_CODES = Object.freeze({
  MISSING_RENDERED_CONTROL: 'MISSING_RENDERED_CONTROL',
  UNDERLAY_REVIEW_FAILED: 'UNDERLAY_REVIEW_FAILED',
  TYPOGRAPHY_GATE_FAILED: 'TYPOGRAPHY_GATE_FAILED',
  COMPONENT_ASSET_UNIDENTIFIED: 'COMPONENT_ASSET_UNIDENTIFIED',
  UNRESOLVED_IDENTITY_FONT: 'UNRESOLVED_IDENTITY_FONT',
  FONT_RENDER_NOT_VERIFIED: 'FONT_RENDER_NOT_VERIFIED',
  FONT_RENDER_HASH_MISMATCH: 'FONT_RENDER_HASH_MISMATCH',
  FONT_RENDER_FAMILY_MISMATCH: 'FONT_RENDER_FAMILY_MISMATCH',
  COMPOSITION_OUTPUT_REFERENCE_MISMATCH: 'COMPOSITION_OUTPUT_REFERENCE_MISMATCH',
  COMPOSITION_OUTPUT_MODE_MISMATCH: 'COMPOSITION_OUTPUT_MODE_MISMATCH',
  // Same token as the pipeline ERROR_CODE: fidelity reports it as an issue
  // code when the Composition Output artifact itself is absent.
  COMPOSITION_OUTPUT_MISSING: 'COMPOSITION_OUTPUT_MISSING',
  STALE_DEPENDENCY: 'STALE_DEPENDENCY',
  // Fidelity Inspector issue codes (manifest-consistency / visual-fidelity)
  COMPONENT_ASSET_UNREADABLE: 'COMPONENT_ASSET_UNREADABLE',
  FONT_ASSET_UNREADABLE: 'FONT_ASSET_UNREADABLE',
  FONT_IDENTITY_MISMATCH: 'FONT_IDENTITY_MISMATCH',
  OUTPUT_SOURCE_MISMATCH: 'OUTPUT_SOURCE_MISMATCH',
  OUTPUT_VERSION_MISMATCH: 'OUTPUT_VERSION_MISMATCH',
  COMPONENT_OVERLAP: 'COMPONENT_OVERLAP',
  FINAL_ALPHA_MISSING: 'FINAL_ALPHA_MISSING',
  FINAL_CANVAS_MISMATCH: 'FINAL_CANVAS_MISMATCH',
  FINAL_PIXELS_EMPTY: 'FINAL_PIXELS_EMPTY',
  LAYER_OUT_OF_BOUNDS: 'LAYER_OUT_OF_BOUNDS',
  NINE_SLICE_FIXED_REGIONS_MISSING: 'NINE_SLICE_FIXED_REGIONS_MISSING',
  NINE_SLICE_FIXED_REGION_DEFORMED: 'NINE_SLICE_FIXED_REGION_DEFORMED',
  RENDERED_BBOX_MISMATCH: 'RENDERED_BBOX_MISMATCH',
  SAFE_AREA_VIOLATION: 'SAFE_AREA_VIOLATION',
  TEXT_OVERFLOW: 'TEXT_OVERFLOW'
});

module.exports = { ERROR_CODES, FIDELITY_ISSUE_CODES, BINDING_VALIDATION_CODES };
